name: cs663_project
dependencies:
    - python=3.6
    - matplotlib
    - numpy
    - opencv
    - Pillow
    - scipy
    - scikit-learn
    - scikit-image
    - requests
    - jupyter
    - requests
    - pip:
        - tensorflow-gpu
        - pyyaml
